title: Cavity-based single photon generation schemes using STIRAP re-preparation
description: J.-R. Alvarez, E. Kassa, T. D. Barrett and A. Kuhn <br/>  University of Oxford, Clarendon Laboratory, Parks Road, Oxford OX1 3PU, United Kingdom 
theme: jekyll-theme-cayman
